### ISSUE TITLE
Login/Logout Management

### ISSUE THREAD

**Issue by krvikas1011** [krvikas1011/shop-keeper#13]
### Acceptance Criteria
- [ ] Create a system to manage user login/logout sessions.
- [ ] This system should be extensible for different types of users in the system for the future.
- [ ] Create the Database structure for this system.
- [ ] Provide basic security for login and password management.
- [ ] Provide password reset options in case of a forgotten password.

#### Sub-Tasks
- [ ] Design Database for Login / Logout - Arshia
